# Generated by Django 5.1.3 on 2025-03-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_alter_reward_points_alter_reward_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='discount_available',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
