# Generated by Django 5.1.3 on 2025-03-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_alter_review_car'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
