# Generated by Django 5.1.6 on 2025-03-17 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_alter_review_rating_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('tour_pakege', 'Tour Package'), ('airport_transfer', 'Airport Transfer'), ('widding_car', 'Widding Car'), ('corporate_rentals', 'Corporate Rentals')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
