# Generated by Django 5.1.6 on 2025-03-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0011_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('tour_pakege', 'Tour-Package'), ('airport_transfer', 'Airport-Transfer'), ('widding_car', 'Widding-Car'), ('corporate_rentals', 'Corporate-Rentals')], max_length=100),
        ),
    ]
