# Generated by Django 5.1.6 on 2025-03-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_alter_car_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('tour-package', 'Tour Package'), ('airport-transfer', 'Airport Transfer'), ('wedding-cars', 'Wedding Cars'), ('corporate-rentals', 'Corporate Rentals')], default='tour-package', max_length=100),
        ),
    ]
