# Generated by Django 5.1.7 on 2025-03-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_alter_car_description_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='id_back',
            field=models.ImageField(null=True, upload_to='id_documents/'),
        ),
        migrations.AddField(
            model_name='customprofile',
            name='id_front',
            field=models.ImageField(null=True, upload_to='id_documents/'),
        ),
    ]
