# Generated by Django 5.1.7 on 2025-03-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0015_customprofile_id_back_customprofile_id_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Chapa', 'Chapa')], default='Chapa', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
