# Generated by Django 5.1.7 on 2025-04-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0018_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customprofile',
            name='id_back',
        ),
        migrations.RemoveField(
            model_name='customprofile',
            name='id_front',
        ),
        migrations.AddField(
            model_name='customprofile',
            name='extracted_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customprofile',
            name='id_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_images/back/'),
        ),
        migrations.AddField(
            model_name='customprofile',
            name='id_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='id_images/front/'),
        ),
    ]
