# Generated by Django 5.1.7 on 2025-05-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0019_remove_customprofile_id_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
