# Generated by Django 5.1.7 on 2025-05-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0020_alter_customprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='id_back_image',
            field=models.ImageField(blank=True, null=True, serialize=False, upload_to='id_images/back/'),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='id_front_image',
            field=models.ImageField(blank=True, null=True, serialize=False, upload_to='id_images/front/'),
        ),
    ]
