# Generated by Django 5.1.7 on 2025-05-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0021_alter_customprofile_id_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=100),
        ),
    ]
